version: "3"

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - laravel

  mariadb:
    image: mariadb:10.2
    ports:
      - "3307:3307"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_TCP_PORT: 3307

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel